const countries =[
  {
    name: "Afghanistan",
    name: "Albania",
    name: "Algeria",
    name: "American Samoa",
    name: "Andorra",
    name: "Angola",
    name: "Anguilla",
    name: "Antigua and Barbuda",
    name: "Argentina",
    name: "Armenia",
    name: "Aruba",
    name: "Australia",
    name: "Austria",
    name: "Azerbaijan",
    name: "Bahamas",
    name: "Bahrain",
    name: "Bangladesh",
    name: "Barbados",
    name: "Belarus",
    name: "Belgium",
    name: "Belize",
    name: "Benin",
    name: "Bermuda",
    name: "Bhutan",
    name: "Bolivia, Plurinational State of",
    name: "Bosnia and Herzegovina",
    name: "Botswana",
    name: "Brazil",
    name: "British Indian Ocean Territory",
    name: "Bulgaria",
    name: "Burkina Faso",
    name: "Burundi",
    name: "Cambodia",
    name: "Cameroon",
    name: "Canada",
    name: "Cape Verde",
    name: "Cayman Islands",
    name: "Central African Republic",
    name: "Chad",
    name: "Chile",
    name: "China",
    name: "Colombia",
    name: "Comoros",
    name: "Congo",
    name: "Democratic Republic of the Congo",
    name: "Cook Islands",
    name: "Costa Rica",
    name: "Côte d'Ivoire",
    name: "Croatia",
    name: "Cuba",
    name: "Curaçao",
    name: "Cyprus",
    name: "Czech Republic",
    name: "Denmark",
    name: "Djibouti",
    name: "Dominica",
    name: "Dominican Republic",
    name: "Ecuador",
    name: "Egypt",
    name: "El Salvador",
    name: "Equatorial Guinea",
    name: "Eritrea",
    name: "Estonia",
    name: "Ethiopia",
    name: "Falkland Islands (Malvinas)",
    name: "Faroe Islands",
    name: "Fiji",
    name: "Finland",
    name: "France",
    name: "French Polynesia",
    name: "Gabon",
    name: "Gambia",
    name: "Georgia",
    name: "Germany",
    name: "Ghana",
    name: "Gibraltar",
    name: "Greece",
    name: "Greenland",
    name: "Grenada",
    name: "Guatemala",
    name: "Guernsey",
    name: "Guinea",
    name: "Guinea-Bissau",
    name: "Haiti",
    name: "Honduras",
    name: "Hong Kong",
    name: "Hungary",
    name: "Iceland",
    name: "India",
    name: "Indonesia",
    name: "Iran, Islamic Republic of",
    name: "Iraq",
    name: "Ireland",
    name: "Isle of Man",
    name: "Israel",
    name: "Italy",
    name: "Jamaica",
    name: "Japan",
    name: "Jersey",
    name: "Jordan",
    name: "Kazakhstan",
    name: "Kenya",
    name: "Kiribati",
    name: "North Korea",
    name: "South Korea",
    name: "Kuwait",
    name: "Kyrgyzstan",
    name: "Lao People's Democratic Republic",
    name: "Latvia",
    name: "Lebanon",
    name: "Lesotho",
    name: "Liberia",
    name: "Libya",
    name: "Liechtenstein",
    name: "Lithuania",
    name: "Luxembourg",
    name: "Macao",
    name: "Republic of Macedonia",
    name: "Madagascar",
    name: "Malawi",
    name: "Malaysia",
    name: "Maldives",
    name: "Mali",
    name: "Malta",
    name: "Marshall Islands",
    name: "Martinique",
    name: "Mauritania",
    name: "Mauritius",
    name: "Mexico",
    name: "Micronesia, Federated States of",
    name: "Republic of Moldova",
    name: "Monaco",
    name: "Mongolia",
    name: "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestinian Territory",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RO": "Romania",
    "RU": "Russian",
    "RW": "Rwanda",
    "KN": "Saint Kitts and Nevis",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SX": "Sint Maarten",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "SS": "South Sudan",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SZ": "Swaziland",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syria",
    "TW": "Taiwan, Province of China",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks and Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela, Bolivarian Republic of",
    "VN": "Viet Nam",
    "VI": "Virgin Islands",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
  }
]
  
  export default countries;
  